[book]
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor.blocks]
command = "node dist/blocks.js"

[output.html]
additional-css = ["mdbook-blocks/resources/bootstrap/scss/bootstrap.css", "mdbook-blocks/resources/blocks/scss/blocks.css"]
additional-js = ["mdbook-blocks/resources/bootstrap/js/bootstrap.js"]
no-section-label = true