[book]
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor.blocks]
command = "node out/blocks.js"

[output.html]
additional-css = ["mdbook-blocks/dependencies/bootstrap/scss/bootstrap.css", "mdbook-blocks/dependencies/blocks/scss/blocks.css"]
additional-js = ["mdbook-blocks/dependencies/bootstrap/js/bootstrap.js"]
no-section-label = true